version: "3"
services:
  webdriverio:
    build: .
    networks:
      - bolstertest
    depends_on:
     - selenium-hub

  selenium-hub:
    image: selenium/hub:3.141.59-zinc
    container_name: selenium-hub
    networks:
      - bolstertest
    depends_on:
      - chromenode
    ports:
      - "4444:4444"
  chromenode:
    image: selenium/node-chrome:3.141.59-zinc
    container_name: chrome-service
    networks:
      - bolstertest
    volumes:
      - /dev/shm:/dev/shm
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
networks:
  bolstertest:
    driver: bridge